services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=emsx
    volumes:
      - postgres_emsx:/var/lib/postgresql/data

    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always

    ports:
      - 9090:8080

volumes:
  postgres_emsx: