import type { Metadata } from "next";

import { AuthProvider } from "./lib/auth-provider";

import { auth } from "@/auth";

import Navbar from "@/app/lib/components/navbar/navbar";

import Footer from "@/app/lib/ui/footer/footer";

import { poppins } from "@/app/lib/ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AuthProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
