import type { Metadata } from "next";

import Navbar from "@/app/lib/components/navbar/navbar";

import Footer from "@/app/lib/ui/footer/footer";

import {poppins} from "@/app/lib/ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>

    </html>
  );
}
