name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like vx.x.x

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract the tag (e.g., vx.x.x)
      - name: Extract tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # Convert repository name to lowercase
      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ env.REPO_NAME }}:latest \
            -t ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }} \
            .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}
